In [1]:
%config ZMQInteractiveShell.ast_node_interactivity='all'
%matplotlib inline
import warnings;warnings.filterwarnings('ignore')
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import metrics
from sklearn.base import BaseEstimator, ClassifierMixin, TransformerMixin, clone
from sklearn.preprocessing import Imputer, LabelEncoder
from sklearn.model_selection import KFold, StratifiedKFold, RandomizedSearchCV
from sklearn.externals import joblib

/Users/Meng/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [2]:
target = '标签'
uid = '申请编号'

In [4]:
############## Load

data_ori= pd.read_csv('./tmp/d12_d30.csv', header=0, index_col=0)
data_ori.shape
data_ori.head()

(140000, 331)

申请编号  标签  贷款类型           信用额度          贷款年金           商品价格  陪同申请人  \
0     0   1     0  460190.889355  17463.042019  419951.511045    7.0   
1     1   0     0  424370.659603  15585.046388  384597.975692    7.0   
2     2   0     0  469330.587153  18837.558252  419951.511045    1.0   
3     3   0     0  464188.353140  16754.587069  409850.500944    7.0   
4     5   0     0  434196.988738  16165.009200  394698.985793    7.0   

   出生日期距申请日期天数  工作日期距申请日期天数  注册日期距申请日期天数  ...  申请时点_6sum  申请时点_6mean  \
0     -10107.0       -342.0      -5421.0  ...        0.0         0.0   
1     -13980.0      -1110.0      -3387.0  ...        0.0         0.0   
2     -13331.0      -2246.0      -3870.0  ...        1.0         0.1   
3     -16540.0          NaN       -970.0  ...        0.0         0.0   
4     -17919.0     -11037.0      -9350.0  ...        1.0         0.2   

   申请时点_7sum  申请时点_7mean  申请时点_8sum  申请时点_8mean  申请时点_9sum  申请时点_9mean  \
0        0.0         0.0        0.0         0.0        1.0         1.0   
1        0.0         0.0        0.0         0.0        0.0         0.0   
2        7.0         0.7        1.0         0.1        1.0         0.1   
3        0.0         0.0        0.0         0.0        0.0         0.0   
4        0.0         0.0        2.0         0.4        1.0         0.2   

   申请时点_othersum  申请时点_othermean  
0            0.0             0.0  
1            2.0             1.0  
2            0.0             0.0  
3            0.0             0.0  
4            0.0             0.0  

[5 rows x 331 columns]

In [6]:
############## Fill Null

# Fill Null
imp =Imputer(missing_values=np.NaN, strategy="mean", axis=0)
data = imp.fit_transform(data_ori)
len(data)
len(data[0])

/Users/Meng/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


140000

331

In [11]:
############## X, y

''' y '''
y = data[:, 1]
len(y)
y[:10]

''' X '''
X = data[:, 2:]
len(X)
len(X[0])
X[0][:10]

pd.DataFrame(y).to_csv('./tmp/1_y.csv')
pd.DataFrame(X).to_csv('./tmp/1_X.csv')

' y '

140000

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

' X '

140000

329

array([ 0.00000000e+00,  4.60190889e+05,  1.74630420e+04,  4.19951511e+05,
        7.00000000e+00, -1.01070000e+04, -3.42000000e+02, -5.42100000e+03,
       -3.29200000e+03,  1.00000000e+00])

In [34]:
############## Check

X1 = pd.read_csv('./tmp/1_X.csv', header=0, index_col=0)
X1.shape
X1.head()

y1 = pd.read_csv('./tmp/1_y.csv', header=0, index_col=0)
y1.shape
y1.head()

''' y '''
len(y)
y2 = y1['0'].values
len(y2)
(y == y2).sum()

''' X '''
len(X)
len(X[0])
X2 = X1.values
len(X2)
len(X2[0])
(X == X2).sum(axis=1)
140000 * 329

' y '

140000

140000

140000

' X '

140000

329

140000

329

array([325, 327, 328, ..., 325, 327, 328])

46060000

In [18]:
n=0
y[n]
y2[n]

1.0

array([1.])